rm -rf ./i_SLLW_III/xHBPerfG_leaving
rm -rf ./i_XOR_III/xCoverAPerflocDiv
rm -rf ./i_XOR_III/xPerfLocCycleCount
rm -rf ./i_XOR_III/xFlushCheck
rm -rf ./i_XOR_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_XOR_III/xHBPerfG_dfg_v3_div
rm -rf ./i_XOR_III/xAggregate
rm -rf ./i_XOR_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_XOR_III/xPersetCycleCount
rm -rf ./i_XOR_III/xPairwiseDepDiv
rm -rf ./i_XOR_III/xPOPLSetsUpdatedCover
rm -rf ./i_XOR_III/xCollectReEval
rm -rf ./i_XOR_III/xPerfLocSubsetDiv
rm -rf ./i_XOR_III/xPOPLSets
rm -rf ./i_XOR_III/xHBPerfG_leaving
rm -rf ./i_XORI_III/xCollectReEval
rm -rf ./i_XORI_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_XORI_III/xHBPerfG_dfg_v3_div
rm -rf ./i_XORI_III/xPerfLocCycleCount
rm -rf ./i_XORI_III/xFlushCheck
rm -rf ./i_XORI_III/xPOPLSetsUpdatedCover
rm -rf ./i_XORI_III/xPerfLocSubsetDiv
rm -rf ./i_XORI_III/xPOPLSets
rm -rf ./i_XORI_III/xPersetCycleCount
rm -rf ./i_XORI_III/xPairwiseDepDiv
rm -rf ./i_XORI_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_XORI_III/xHBPerfG_leaving
rm -rf ./i_XORI_III/xAggregate
rm -rf ./i_XORI_III/xCoverAPerflocDiv
rm -rf ./i_DIVW_III/xPersetCycleCount
rm -rf ./i_DIVW_III/xPairwiseDepDiv
rm -rf ./i_DIVW_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_DIVW_III/xAggregate
rm -rf ./i_DIVW_III/xCoverAPerflocDiv
rm -rf ./i_DIVW_III/xHBPerfG_dfg_v3_div
rm -rf ./i_DIVW_III/xCollectReEval
rm -rf ./i_DIVW_III/xPerfLocCycleCount
rm -rf ./i_DIVW_III/xHBPerfG_leaving
rm -rf ./i_DIVW_III/xFlushCheck
rm -rf ./i_DIVW_III/xPOPLSetsUpdatedCover
rm -rf ./i_DIVW_III/xPOPLSets
rm -rf ./i_DIVW_III/xPerfLocSubsetDiv
rm -rf ./i_DIVW_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_SLT_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_SLT_III/xPairwiseDepDiv
rm -rf ./i_SLT_III/xPersetCycleCount
rm -rf ./i_SLT_III/xCoverAPerflocDiv
rm -rf ./i_SLT_III/xFlushCheck
rm -rf ./i_SLT_III/xAggregate
rm -rf ./i_SLT_III/xCollectReEval
rm -rf ./i_SLT_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_SLT_III/xHBPerfG_leaving
rm -rf ./i_SLT_III/xPOPLSets
rm -rf ./i_SLT_III/xHBPerfG_dfg_v3_div
rm -rf ./i_SLT_III/xPerfLocSubsetDiv
rm -rf ./i_SLT_III/xPOPLSetsUpdatedCover
rm -rf ./i_SLT_III/xPerfLocCycleCount
rm -rf ./i_SRLIW_III/xPOPLSets
rm -rf ./i_SRLIW_III/xCoverAPerflocDiv
rm -rf ./i_SRLIW_III/xHBPerfG_leaving
rm -rf ./i_SRLIW_III/xFlushCheck
rm -rf ./i_SRLIW_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_SRLIW_III/xAggregate
rm -rf ./i_SRLIW_III/xPersetCycleCount
rm -rf ./i_SRLIW_III/xPerfLocSubsetDiv
rm -rf ./i_SRLIW_III/xHBPerfG_dfg_v3_div
rm -rf ./i_SRLIW_III/xPOPLSetsUpdatedCover
rm -rf ./i_SRLIW_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_SRLIW_III/xPairwiseDepDiv
rm -rf ./i_SRLIW_III/xCollectReEval
rm -rf ./i_SRLIW_III/xPerfLocCycleCount
rm -rf ./i_REMW_III/xPOPLSetsUpdatedCover
rm -rf ./i_REMW_III/xCollectReEval
rm -rf ./i_REMW_III/xCoverAPerflocDiv
rm -rf ./i_REMW_III/xPerfLocCycleCount
rm -rf ./i_REMW_III/xHBPerfG_dfg_v3_div
rm -rf ./i_REMW_III/xPersetCycleCount
rm -rf ./i_REMW_III/xAggregate
rm -rf ./i_REMW_III/xHBPerfG_leaving
rm -rf ./i_REMW_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_REMW_III/xPerfLocSubsetDiv
rm -rf ./i_REMW_III/xFlushCheck
rm -rf ./i_REMW_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_REMW_III/xPOPLSets
rm -rf ./i_REMW_III/xPairwiseDepDiv
rm -rf ./i_SLTIU_III/xPairwiseDepDiv
rm -rf ./i_SLTIU_III/xPOPLSetsUpdatedCover
rm -rf ./i_SLTIU_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_SLTIU_III/xPerfLocSubsetDiv
rm -rf ./i_SLTIU_III/xHBPerfG_dfg_v3_div
rm -rf ./i_SLTIU_III/xHBPerfG_leaving
rm -rf ./i_SLTIU_III/xPOPLSets
rm -rf ./i_SLTIU_III/xFlushCheck
rm -rf ./i_SLTIU_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_SLTIU_III/xPersetCycleCount
rm -rf ./i_SLTIU_III/xAggregate
rm -rf ./i_SLTIU_III/xPerfLocCycleCount
rm -rf ./i_SLTIU_III/xCollectReEval
rm -rf ./i_SLTIU_III/xCoverAPerflocDiv
rm -rf ./i_SLL_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_SLL_III/xPairwiseDepDiv
rm -rf ./i_SLL_III/xPOPLSetsUpdatedCover
rm -rf ./i_SLL_III/xPersetCycleCount
rm -rf ./i_SLL_III/xCoverAPerflocDiv
rm -rf ./i_SLL_III/xCollectReEval
rm -rf ./i_SLL_III/xPOPLSets
rm -rf ./i_SLL_III/xFlushCheck
rm -rf ./i_SLL_III/xHBPerfG_leaving
rm -rf ./i_SLL_III/xAggregate
rm -rf ./i_SLL_III/xPerfLocCycleCount
rm -rf ./i_SLL_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_SLL_III/xHBPerfG_dfg_v3_div
rm -rf ./i_SLL_III/xPerfLocSubsetDiv
rm -rf ./i_ECALL_III/xPerfLocCycleCount
rm -rf ./i_ECALL_III/xPairwiseDepDiv
rm -rf ./i_ECALL_III/xPerfLocSubsetDiv
rm -rf ./i_ECALL_III/xCollectReEval
rm -rf ./i_ECALL_III/xHBPerfG_leaving
rm -rf ./i_ECALL_III/xCoverAPerflocDiv
rm -rf ./i_ECALL_III/xHBPerfG_dfg_v3_div
rm -rf ./i_SUB_III/xAggregate
rm -rf ./i_SUB_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_SUB_III/xCoverAPerflocDiv
rm -rf ./i_SUB_III/xPOPLSets
rm -rf ./i_SUB_III/xHBPerfG_dfg_v3_div
rm -rf ./i_SUB_III/xPOPLSetsUpdatedCover
rm -rf ./i_SUB_III/xPersetCycleCount
rm -rf ./i_SUB_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_SUB_III/xPerfLocSubsetDiv
rm -rf ./i_SUB_III/xHBPerfG_leaving
rm -rf ./i_SUB_III/xPairwiseDepDiv
rm -rf ./i_SUB_III/xCollectReEval
rm -rf ./i_SUB_III/xFlushCheck
rm -rf ./i_SUB_III/xPerfLocCycleCount
rm -rf ./i_SD_III/xPOPLSets
rm -rf ./i_SD_III/xPersetCycleCount
rm -rf ./i_SD_III/xCollectReEval
rm -rf ./i_SD_III/xCoverAPerflocDiv
rm -rf ./i_SD_III/xPairwiseDepDiv
rm -rf ./i_SD_III/xAggregate
rm -rf ./i_SD_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_SD_III/xPerfLocCycleCount
rm -rf ./i_SD_III/xHBPerfG_leaving
rm -rf ./i_SD_III/xFlushCheck
rm -rf ./i_SD_III/xHBPerfG_dfg_v3_div
rm -rf ./i_SD_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_SD_III/xPOPLSetsUpdatedCover
rm -rf ./i_SD_III/xPerfLocSubsetDiv
rm -rf ./i_SUBW_III/xPairwiseDepDiv
rm -rf ./i_SUBW_III/xFlushCheck
rm -rf ./i_SUBW_III/xHBPerfG_dfg_v3_div
rm -rf ./i_SUBW_III/xHBPerfG_leaving
rm -rf ./i_SUBW_III/xPerfLocSubsetDiv
rm -rf ./i_SUBW_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_SUBW_III/xPersetCycleCount
rm -rf ./i_SUBW_III/xPerfLocCycleCount
rm -rf ./i_SUBW_III/xPOPLSets
rm -rf ./i_SUBW_III/xCoverAPerflocDiv
rm -rf ./i_SUBW_III/xPOPLSetsUpdatedCover
rm -rf ./i_SUBW_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_SUBW_III/xAggregate
rm -rf ./i_SUBW_III/xCollectReEval
rm -rf ./i_CSRRW_III/xCoverAPerflocDiv
rm -rf ./i_CSRRW_III/xHBPerfG_leaving
rm -rf ./i_CSRRW_III/xPairwiseDepDiv
rm -rf ./i_CSRRW_III/xCollectReEval
rm -rf ./i_CSRRW_III/xPerfLocCycleCount
rm -rf ./i_CSRRW_III/xPerfLocSubsetDiv
rm -rf ./i_CSRRW_III/xHBPerfG_dfg_v3_div
rm -rf ./i_SLTU_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_SLTU_III/xHBPerfG_leaving
rm -rf ./i_SLTU_III/xPersetCycleCount
rm -rf ./i_SLTU_III/xPOPLSets
rm -rf ./i_SLTU_III/xCoverAPerflocDiv
rm -rf ./i_SLTU_III/xAggregate
rm -rf ./i_SLTU_III/xPerfLocCycleCount
rm -rf ./i_SLTU_III/xPairwiseDepDiv
rm -rf ./i_SLTU_III/xFlushCheck
rm -rf ./i_SLTU_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_SLTU_III/xPerfLocSubsetDiv
rm -rf ./i_SLTU_III/xHBPerfG_dfg_v3_div
rm -rf ./i_SLTU_III/xPOPLSetsUpdatedCover
rm -rf ./i_SLTU_III/xCollectReEval
rm -rf ./i_FENCE_III/xPerfLocCycleCount
rm -rf ./i_FENCE_III/xPairwiseDepDiv
rm -rf ./i_FENCE_III/xPerfLocSubsetDiv
rm -rf ./i_FENCE_III/xCollectReEval
rm -rf ./i_FENCE_III/xHBPerfG_leaving
rm -rf ./i_FENCE_III/xCoverAPerflocDiv
rm -rf ./i_FENCE_III/xHBPerfG_dfg_v3_div
rm -rf ./i_SRLW_III/xPerfLocSubsetDiv
rm -rf ./i_SRLW_III/xCollectReEval
rm -rf ./i_SRLW_III/xPerfLocCycleCount
rm -rf ./i_SRLW_III/xPairwiseDepDiv
rm -rf ./i_SRLW_III/xAggregate
rm -rf ./i_SRLW_III/xPOPLSetsUpdatedCover
rm -rf ./i_SRLW_III/xHBPerfG_leaving
rm -rf ./i_SRLW_III/xPOPLSets
rm -rf ./i_SRLW_III/xHBPerfG_dfg_v3_div
rm -rf ./i_SRLW_III/xCoverAPerflocDiv
rm -rf ./i_SRLW_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_SRLW_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_SRLW_III/xFlushCheck
rm -rf ./i_SRLW_III/xPersetCycleCount
rm -rf ./i_REM_III/xCollectReEval
rm -rf ./i_REM_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_REM_III/xAggregate
rm -rf ./i_REM_III/xPerfLocSubsetDiv
rm -rf ./i_REM_III/xPOPLSetsUpdatedCover
rm -rf ./i_REM_III/xFlushCheck
rm -rf ./i_REM_III/xPersetCycleCount
rm -rf ./i_REM_III/xPOPLSets
rm -rf ./i_REM_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_REM_III/xPerfLocCycleCount
rm -rf ./i_REM_III/xHBPerfG_dfg_v3_div
rm -rf ./i_REM_III/xHBPerfG_leaving
rm -rf ./i_REM_III/xCoverAPerflocDiv
rm -rf ./i_REM_III/xPairwiseDepDiv
rm -rf ./i_BGE_III/xPOPLSetsUpdatedCover
rm -rf ./i_BGE_III/xCollectReEval
rm -rf ./i_BGE_III/xHBPerfG_leaving
rm -rf ./i_BGE_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_BGE_III/xCoverAPerflocDiv
rm -rf ./i_BGE_III/xPerfLocCycleCount
rm -rf ./i_BGE_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_BGE_III/xPersetCycleCount
rm -rf ./i_BGE_III/xPerfLocSubsetDiv
rm -rf ./i_BGE_III/xAggregate
rm -rf ./i_BGE_III/xHBPerfG_dfg_v3_div
rm -rf ./i_BGE_III/xPOPLSets
rm -rf ./i_BGE_III/xFlushCheck
rm -rf ./i_BGE_III/xPairwiseDepDiv
rm -rf ./i_SLTI_III/xFlushCheck
rm -rf ./i_SLTI_III/xHBPerfG_leaving
rm -rf ./i_SLTI_III/xCollectReEval
rm -rf ./i_SLTI_III/xPairwiseDepDiv
rm -rf ./i_SLTI_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_SLTI_III/xPOPLSetsUpdatedCover
rm -rf ./i_SLTI_III/xPerfLocSubsetDiv
rm -rf ./i_SLTI_III/xPersetCycleCount
rm -rf ./i_SLTI_III/xPOPLSets
rm -rf ./i_SLTI_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_SLTI_III/xHBPerfG_dfg_v3_div
rm -rf ./i_SLTI_III/xCoverAPerflocDiv
rm -rf ./i_SLTI_III/xPerfLocCycleCount
rm -rf ./i_SLTI_III/xAggregate
rm -rf ./i_DIV_III/xHBPerfG_leaving
rm -rf ./i_DIV_III/xPOPLSets
rm -rf ./i_DIV_III/xAggregate
rm -rf ./i_DIV_III/xPOPLSetsUpdatedCover
rm -rf ./i_DIV_III/xFlushCheck
rm -rf ./i_DIV_III/xPerfLocSubsetDiv
rm -rf ./i_DIV_III/xCollectReEval
rm -rf ./i_DIV_III/xPerfLocCycleCount
rm -rf ./i_DIV_III/xPersetCycleCount
rm -rf ./i_DIV_III/xHBPerfG_dfg_v3_div
rm -rf ./i_DIV_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_DIV_III/xPairwiseDepDiv
rm -rf ./i_DIV_III/xCoverAPerflocDiv
rm -rf ./i_DIV_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_LHU_III/xHBPerfG_dfg_v3_div
rm -rf ./i_LHU_III/xPOPLSets
rm -rf ./i_LHU_III/xHBPerfG_leaving
rm -rf ./i_LHU_III/xPerfLocCycleCount
rm -rf ./i_LHU_III/xPerfLocSubsetDiv
rm -rf ./i_LHU_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_LHU_III/xCoverAPerflocDiv
rm -rf ./i_LHU_III/xPOPLSetsUpdatedCover
rm -rf ./i_LHU_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_LHU_III/xFlushCheck
rm -rf ./i_LHU_III/xPairwiseDepDiv
rm -rf ./i_LHU_III/xPersetCycleCount
rm -rf ./i_LHU_III/xCollectReEval
rm -rf ./i_LHU_III/xAggregate
rm -rf ./i_SLLI_III/xHBPerfG_leaving
rm -rf ./i_SLLI_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_SLLI_III/xPerfLocSubsetDiv
rm -rf ./i_SLLI_III/xPOPLSets
rm -rf ./i_SLLI_III/xHBPerfG_dfg_v3_div
rm -rf ./i_SLLI_III/xPerfLocCycleCount
rm -rf ./i_SLLI_III/xCollectReEval
rm -rf ./i_SLLI_III/xCoverAPerflocDiv
rm -rf ./i_SLLI_III/xPairwiseDepDiv
rm -rf ./i_SLLI_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_SLLI_III/xPOPLSetsUpdatedCover
rm -rf ./i_SLLI_III/xPersetCycleCount
rm -rf ./i_SLLI_III/xAggregate
rm -rf ./i_SLLI_III/xFlushCheck
rm -rf ./i_BLT_III/xAggregate
rm -rf ./i_BLT_III/xCollectReEval
rm -rf ./i_BLT_III/xPerfLocCycleCount
rm -rf ./i_BLT_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_BLT_III/xCoverAPerflocDiv
rm -rf ./i_BLT_III/xHBPerfG_dfg_v3_div
rm -rf ./i_BLT_III/xPersetCycleCount
rm -rf ./i_BLT_III/xFlushCheck
rm -rf ./i_BLT_III/xHBPerfG_leaving
rm -rf ./i_BLT_III/xPerfLocSubsetDiv
rm -rf ./i_BLT_III/xPairwiseDepDiv
rm -rf ./i_BLT_III/xPOPLSets
rm -rf ./i_BLT_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_BLT_III/xPOPLSetsUpdatedCover
rm -rf ./i_REMU_III/xHBPerfG_dfg_v3_div
rm -rf ./i_REMU_III/xPairwiseDepDiv
rm -rf ./i_REMU_III/xPOPLSetsUpdatedCover
rm -rf ./i_REMU_III/xPerfLocSubsetDiv
rm -rf ./i_REMU_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_REMU_III/xHBPerfG_leaving
rm -rf ./i_REMU_III/xPersetCycleCount
rm -rf ./i_REMU_III/xCollectReEval
rm -rf ./i_REMU_III/xPOPLSets
rm -rf ./i_REMU_III/xPerfLocCycleCount
rm -rf ./i_REMU_III/xFlushCheck
rm -rf ./i_REMU_III/xCoverAPerflocDiv
rm -rf ./i_REMU_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_REMU_III/xAggregate
rm -rf ./i_SB_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_SB_III/xPerfLocCycleCount
rm -rf ./i_SB_III/xFlushCheck
rm -rf ./i_SB_III/xPersetCycleCount
rm -rf ./i_SB_III/xPairwiseDepDiv
rm -rf ./i_SB_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_SB_III/xCoverAPerflocDiv
rm -rf ./i_SB_III/xHBPerfG_dfg_v3_div
rm -rf ./i_SB_III/xCollectReEval
rm -rf ./i_SB_III/xAggregate
rm -rf ./i_SB_III/xHBPerfG_leaving
rm -rf ./i_SB_III/xPerfLocSubsetDiv
rm -rf ./i_SB_III/xPOPLSets
rm -rf ./i_SB_III/xPOPLSetsUpdatedCover
rm -rf ./i_SRA_III/xPerfLocCycleCount
rm -rf ./i_SRA_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_SRA_III/xFlushCheck
rm -rf ./i_SRA_III/xPersetCycleCount
rm -rf ./i_SRA_III/xPOPLSets
rm -rf ./i_SRA_III/xCoverAPerflocDiv
rm -rf ./i_SRA_III/xAggregate
rm -rf ./i_SRA_III/xHBPerfG_leaving
rm -rf ./i_SRA_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_SRA_III/xPairwiseDepDiv
rm -rf ./i_SRA_III/xPOPLSetsUpdatedCover
rm -rf ./i_SRA_III/xPerfLocSubsetDiv
rm -rf ./i_SRA_III/xCollectReEval
rm -rf ./i_SRA_III/xHBPerfG_dfg_v3_div
rm -rf ./i_MULHSU_III/xPOPLSetsUpdatedCover
rm -rf ./i_MULHSU_III/xAggregate
rm -rf ./i_MULHSU_III/xHBPerfG_leaving
rm -rf ./i_MULHSU_III/xPerfLocCycleCount
rm -rf ./i_MULHSU_III/xCollectReEval
rm -rf ./i_MULHSU_III/xCoverAPerflocDiv
rm -rf ./i_MULHSU_III/xHBPerfG_dfg_v3_div
rm -rf ./i_MULHSU_III/xPersetCycleCount
rm -rf ./i_MULHSU_III/xPOPLSets
rm -rf ./i_MULHSU_III/xPerfLocSubsetDiv
rm -rf ./i_MULHSU_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_MULHSU_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_MULHSU_III/xFlushCheck
rm -rf ./i_MULHSU_III/xPairwiseDepDiv
rm -rf ./i_AND_III/xCoverAPerflocDiv
rm -rf ./i_AND_III/xPerfLocCycleCount
rm -rf ./i_AND_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_AND_III/xPersetCycleCount
rm -rf ./i_AND_III/xFlushCheck
rm -rf ./i_AND_III/xHBPerfG_leaving
rm -rf ./i_AND_III/xPairwiseDepDiv
rm -rf ./i_AND_III/xAggregate
rm -rf ./i_AND_III/xPOPLSetsUpdatedCover
rm -rf ./i_AND_III/xPerfLocSubsetDiv
rm -rf ./i_AND_III/xPOPLSets
rm -rf ./i_AND_III/xCollectReEval
rm -rf ./i_AND_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_AND_III/xHBPerfG_dfg_v3_div
rm -rf ./i_SW_III/xAggregate
rm -rf ./i_SW_III/xCollectReEval
rm -rf ./i_SW_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_SW_III/xPerfLocSubsetDiv
rm -rf ./i_SW_III/xHBPerfG_leaving
rm -rf ./i_SW_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_SW_III/xPOPLSets
rm -rf ./i_SW_III/xHBPerfG_dfg_v3_div
rm -rf ./i_SW_III/xPerfLocCycleCount
rm -rf ./i_SW_III/xPairwiseDepDiv
rm -rf ./i_SW_III/xPersetCycleCount
rm -rf ./i_SW_III/xFlushCheck
rm -rf ./i_SW_III/xCoverAPerflocDiv
rm -rf ./i_SW_III/xPOPLSetsUpdatedCover
rm -rf ./i_DIVU_III/xPerfLocSubsetDiv
rm -rf ./i_DIVU_III/xHBPerfG_leaving
rm -rf ./i_DIVU_III/xPerfLocCycleCount
rm -rf ./i_DIVU_III/xPOPLSetsUpdatedCover
rm -rf ./i_DIVU_III/xFlushCheck
rm -rf ./i_DIVU_III/xHBPerfG_dfg_v3_div
rm -rf ./i_DIVU_III/xCoverAPerflocDiv
rm -rf ./i_DIVU_III/xPOPLSets
rm -rf ./i_DIVU_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_DIVU_III/xCollectReEval
rm -rf ./i_DIVU_III/xPersetCycleCount
rm -rf ./i_DIVU_III/xAggregate
rm -rf ./i_DIVU_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_DIVU_III/xPairwiseDepDiv
rm -rf ./i_BLTU_III/xFlushCheck
rm -rf ./i_BLTU_III/xCoverAPerflocDiv
rm -rf ./i_BLTU_III/xAggregate
rm -rf ./i_BLTU_III/xPerfLocCycleCount
rm -rf ./i_BLTU_III/xPersetCycleCount
rm -rf ./i_BLTU_III/xPerfLocSubsetDiv
rm -rf ./i_BLTU_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_BLTU_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_BLTU_III/xPOPLSetsUpdatedCover
rm -rf ./i_BLTU_III/xPOPLSets
rm -rf ./i_BLTU_III/xCollectReEval
rm -rf ./i_BLTU_III/xPairwiseDepDiv
rm -rf ./i_BLTU_III/xHBPerfG_leaving
rm -rf ./i_BLTU_III/xHBPerfG_dfg_v3_div
rm -rf ./i_LUI_III/xHBPerfG_dfg_v3_div
rm -rf ./i_LUI_III/xAggregate
rm -rf ./i_LUI_III/xCollectReEval
rm -rf ./i_LUI_III/xPerfLocCycleCount
rm -rf ./i_LUI_III/xPerfLocSubsetDiv
rm -rf ./i_LUI_III/xPairwiseDepDiv
rm -rf ./i_LUI_III/xPersetCycleCount
rm -rf ./i_LUI_III/xFlushCheck
rm -rf ./i_LUI_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_LUI_III/xCoverAPerflocDiv
rm -rf ./i_LUI_III/xPOPLSets
rm -rf ./i_LUI_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_LUI_III/xPOPLSetsUpdatedCover
rm -rf ./i_LUI_III/xHBPerfG_leaving
rm -rf ./i_MULHU_III/xPairwiseDepDiv
rm -rf ./i_MULHU_III/xHBPerfG_dfg_v3_div
rm -rf ./i_MULHU_III/xPersetCycleCount
rm -rf ./i_MULHU_III/xPOPLSets
rm -rf ./i_MULHU_III/xAggregate
rm -rf ./i_MULHU_III/xFlushCheck
rm -rf ./i_MULHU_III/xHBPerfG_leaving
rm -rf ./i_MULHU_III/xCoverAPerflocDiv
rm -rf ./i_MULHU_III/xPerfLocCycleCount
rm -rf ./i_MULHU_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_MULHU_III/xCollectReEval
rm -rf ./i_MULHU_III/xPOPLSetsUpdatedCover
rm -rf ./i_MULHU_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_MULHU_III/xPerfLocSubsetDiv
rm -rf ./i_JAL_III/xCollectReEval
rm -rf ./i_JAL_III/xPersetCycleCount
rm -rf ./i_JAL_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_JAL_III/xFlushCheck
rm -rf ./i_JAL_III/xHBPerfG_leaving
rm -rf ./i_JAL_III/xPerfLocCycleCount
rm -rf ./i_JAL_III/xCoverAPerflocDiv
rm -rf ./i_JAL_III/xHBPerfG_dfg_v3_div
rm -rf ./i_JAL_III/xPOPLSetsUpdatedCover
rm -rf ./i_JAL_III/xPOPLSets
rm -rf ./i_JAL_III/xPairwiseDepDiv
rm -rf ./i_JAL_III/xAggregate
rm -rf ./i_JAL_III/xPerfLocSubsetDiv
rm -rf ./i_JAL_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_LH_III/xPersetCycleCount
rm -rf ./i_LH_III/xPairwiseDepDiv
rm -rf ./i_LH_III/xPerfLocCycleCount
rm -rf ./i_LH_III/xCoverAPerflocDiv
rm -rf ./i_LH_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_LH_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_LH_III/xPOPLSets
rm -rf ./i_LH_III/xHBPerfG_leaving
rm -rf ./i_LH_III/xHBPerfG_dfg_v3_div
rm -rf ./i_LH_III/xFlushCheck
rm -rf ./i_LH_III/xPOPLSetsUpdatedCover
rm -rf ./i_LH_III/xCollectReEval
rm -rf ./i_LH_III/xPerfLocSubsetDiv
rm -rf ./i_LH_III/xAggregate
rm -rf ./i_ADDI_III/xPOPLSetsUpdatedCover
rm -rf ./i_ADDI_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_ADDI_III/xFlushCheck
rm -rf ./i_ADDI_III/xPerfLocSubsetDiv
rm -rf ./i_ADDI_III/xPerfLocCycleCount
rm -rf ./i_ADDI_III/xHBPerfG_dfg_v3_div
rm -rf ./i_ADDI_III/xPairwiseDepDiv
rm -rf ./i_ADDI_III/xHBPerfG_leaving
rm -rf ./i_ADDI_III/xCollectReEval
rm -rf ./i_ADDI_III/xCoverAPerflocDiv
rm -rf ./i_ADDI_III/xPOPLSets
rm -rf ./i_ADDI_III/xAggregate
rm -rf ./i_ADDI_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_ADDI_III/xPersetCycleCount
rm -rf ./i_SRAW_III/xFlushCheck
rm -rf ./i_SRAW_III/xCollectReEval
rm -rf ./i_SRAW_III/xHBPerfG_leaving
rm -rf ./i_SRAW_III/xPOPLSets
rm -rf ./i_SRAW_III/xPairwiseDepDiv
rm -rf ./i_SRAW_III/xPerfLocCycleCount
rm -rf ./i_SRAW_III/xPerfLocSubsetDiv
rm -rf ./i_SRAW_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_SRAW_III/xAggregate
rm -rf ./i_SRAW_III/xPersetCycleCount
rm -rf ./i_SRAW_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_SRAW_III/xPOPLSetsUpdatedCover
rm -rf ./i_SRAW_III/xHBPerfG_dfg_v3_div
rm -rf ./i_SRAW_III/xCoverAPerflocDiv
rm -rf ./i_CSRRC_III/xCoverAPerflocDiv
rm -rf ./i_CSRRC_III/xHBPerfG_dfg_v3_div
rm -rf ./i_CSRRC_III/xHBPerfG_leaving
rm -rf ./i_CSRRC_III/xPerfLocSubsetDiv
rm -rf ./i_CSRRC_III/xCollectReEval
rm -rf ./i_CSRRC_III/xPairwiseDepDiv
rm -rf ./i_CSRRC_III/xPerfLocCycleCount
rm -rf ./i_BNE_III/xPairwiseDepDiv
rm -rf ./i_BNE_III/xPerfLocCycleCount
rm -rf ./i_BNE_III/xHBPerfG_leaving
rm -rf ./i_BNE_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_BNE_III/xCollectReEval
rm -rf ./i_BNE_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_BNE_III/xPerfLocSubsetDiv
rm -rf ./i_BNE_III/xAggregate
rm -rf ./i_BNE_III/xPOPLSets
rm -rf ./i_BNE_III/xFlushCheck
rm -rf ./i_BNE_III/xPOPLSetsUpdatedCover
rm -rf ./i_BNE_III/xPersetCycleCount
rm -rf ./i_BNE_III/xHBPerfG_dfg_v3_div
rm -rf ./i_BNE_III/xCoverAPerflocDiv
rm -rf ./i_AUIPC_III/xPOPLSetsUpdatedCover
rm -rf ./i_AUIPC_III/xPairwiseDepDiv
rm -rf ./i_AUIPC_III/xAggregate
rm -rf ./i_AUIPC_III/xFlushCheck
rm -rf ./i_AUIPC_III/xPerfLocSubsetDiv
rm -rf ./i_AUIPC_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_AUIPC_III/xCollectReEval
rm -rf ./i_AUIPC_III/xCoverAPerflocDiv
rm -rf ./i_AUIPC_III/xHBPerfG_leaving
rm -rf ./i_AUIPC_III/xHBPerfG_dfg_v3_div
rm -rf ./i_AUIPC_III/xPersetCycleCount
rm -rf ./i_AUIPC_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_AUIPC_III/xPOPLSets
rm -rf ./i_AUIPC_III/xPerfLocCycleCount
rm -rf ./i_MULH_III/xPOPLSets
rm -rf ./i_MULH_III/xPersetCycleCount
rm -rf ./i_MULH_III/xCollectReEval
rm -rf ./i_MULH_III/xFlushCheck
rm -rf ./i_MULH_III/xAggregate
rm -rf ./i_MULH_III/xPerfLocCycleCount
rm -rf ./i_MULH_III/xPOPLSetsUpdatedCover
rm -rf ./i_MULH_III/xCoverAPerflocDiv
rm -rf ./i_MULH_III/xPairwiseDepDiv
rm -rf ./i_MULH_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_MULH_III/xHBPerfG_leaving
rm -rf ./i_MULH_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_MULH_III/xPerfLocSubsetDiv
rm -rf ./i_MULH_III/xHBPerfG_dfg_v3_div
rm -rf ./i_ADDIW_III/xCollectReEval
rm -rf ./i_ADDIW_III/xHBPerfG_dfg_v3_div
rm -rf ./i_ADDIW_III/xPairwiseDepDiv
rm -rf ./i_ADDIW_III/xPerfLocSubsetDiv
rm -rf ./i_ADDIW_III/xFlushCheck
rm -rf ./i_ADDIW_III/xPOPLSetsUpdatedCover
rm -rf ./i_ADDIW_III/xPerfLocCycleCount
rm -rf ./i_ADDIW_III/xHBPerfG_leaving
rm -rf ./i_ADDIW_III/xCoverAPerflocDiv
rm -rf ./i_ADDIW_III/xPerfLocSubsetDivCoverTestUndet
rm -rf ./i_ADDIW_III/xPerfLocSubsetDivCoverTest
rm -rf ./i_ADDIW_III/xPersetCycleCount
rm -rf ./i_ADDIW_III/xAggregate
rm -rf ./i_ADDIW_III/xPOPLSets
